### PR TITLE
Monday hours are 9:00am-6:00pm

### PR DESCRIPTION
**Pull request by chriskuehl**

### CODE REVIEW

**Comment by Baisang** [comment]
ok

**Comment by chriskuehl** [comment]
thx

**Comment by jvperrin** [comment]
Unfortunately looks like I can't retroactively approve :P

**Comment by chriskuehl** [comment]
`¯\______(ツ)______/`

**Comment by chriskuehl** [comment]
`¯`

**Comment by jvperrin** [comment]
Lol nice

**Comment by Baisang** [comment]
ckuehl was just trying to spread the wealth, now both of us get commits on ocflib and make our github repository even greener

**Pull request merged**
