### PR TITLE
reserve guest as a username

### PR DESCRIPTION
**Pull request by Baisang**
since we are adding shortlink /guest

see https://github.com/ocf/puppet/pull/185

### CODE REVIEW

**Comment by Baisang** [comment]
wait why did this fail @jvperrin ?

**Comment by jvperrin** [comment]
It looks like it didn't like the slash in the branch name for some reason?

**Comment by jvperrin** [comment]
Probably because it makes a new directory per branch and having a slash in the branch name does not map well to having a directory named after it... Kinda annoying, but using a hyphen or something should fix it.

**Comment by Baisang** [comment]
oh, i see what happened. yeah it looks like its html encoding the '/' because otherwise directories and stuff and yeah.

oh well should work i think

**Pull request merged**
