### PR TITLE
Ticket #5941 distributing constant.py into each respective files

### PR DESCRIPTION
**Pull request by MrMinos**

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
Once this is finished, we still can't merge until ocfweb, utils, etc. are updated.

**Comment by jvperrin** [comment]
Not quite, this just adds duplicate constants, it doesn't remove them from the constants file, so it can be merged and the full file of constants can be removed later once everything is migrated.

**Comment by MrMinos** [comment]
Someone merge this for me please, or add me into ocf github organization!

**Comment by jvperrin** [comment]
I invited you, sorry, should have done that before

**Pull request merged**
