### PR TITLE
Remove py34 from reaper build, bump venv-update

### PR DESCRIPTION
**Pull request by chriskuehl**

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
Why does the py 3.5 test fail to run?

**Comment by chriskuehl** [comment]
venv-update is uninstalling pkg_resources for some reason

**Comment by chriskuehl** [comment]
https://github.com/Yelp/venv-update/issues/186

**Comment by jvperrin** [comment]
I was just trying to debug this too, honestly I have no idea how this all works though, so I wasn't getting very far with it.

**Comment by chriskuehl** [comment]
Blocked on the dumb thing where we download mariadb-server .debs and extract them.

Let's just install mariadb-server everywhere.

**Comment by chriskuehl** [comment]
Still failing, I guess something changed with the MySQL version bump. I'll try to debug locally on reaper.

**Pull request merged**
