### PR TITLE
move create pubkey to __init__ from constants

### PR DESCRIPTION
**Pull request by tahabi**
this is used in ocfweb/account/register.py and approve, pushing those PRs as well

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
High quality commit message.

**Comment by tahabi** [comment]
lol

better?

**Comment by matthew-mcallister** [comment]
Meh, marginally.

**Comment by tahabi** [comment]
care to suggest a better one?

**Comment by jvperrin** [comment]
I take that back on the explicit import part, since it still is, but I do think it would be clearer if it wasn't in `__init__` since we don't tend to put constants there and the public key is used for account creation anyway.

**Comment by tahabi** [comment]
It seemed cleaner to put it in __init__ but I don't have any particularly strong opinions on the topic

**Comment by chriskuehl** [comment]
i agree, imo the only thing that should ever go in `__init__.py` is imports (and then only when you're trying to create an explicit public API, the way `ldap3` or `requests` does it)

people don't expect to find code in `__init__.py` which is a good reason not to put it there

**Pull request merged**
