### PR TITLE
Update Jenkinsfile

### PR DESCRIPTION
**Pull request by singingtelegram**
Build for bullseye

### CODE REVIEW

**Comment by ethanhs** [comment]
We need a base image before this will work

**Comment by singingtelegram** [comment]
Built, see ocf/dockers.

**Review by ethanwu10 — CHANGES_REQUESTED** [review]
We should resolve [build failures](https://jenkins.ocf.berkeley.edu/blue/organizations/jenkins/ocf%2Fdockers/detail/master/514/pipeline#step-35-log-1843) in ocf/dockers first

**Comment by ethanwu10** [comment]
Turns out the build failures are from [autoclean-docker](https://github.com/ocf/puppet/blob/master/modules/ocf_jenkins/files/autoclean-docker) deleting the temp image while the job was in the middle of building since reaper had <25% free disk on `/`. I'll open a new issue for that on puppet, but this PR seems good to me.

**Review by ethanwu10 — APPROVED** [review]

**Pull request merged**
